//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public class Forces
		{
		private double Fy1, Fy2; //Front and rear wheel force
		private double a, b;
		public Forces (double Fy1, double Fy2, double a, double b)
		{
			this.Fy1 = Fy1;
			this.Fy2 = Fy2;
			this.a = a;
			this.b = b;

		}
		public double FyTotal()
		{
			return Fy1 + Fy2;
		}
		public double MzMoment()
		{
			double n1 = Fy1 * a;
			double n2 = Fy2 * b;
			return n1 - n2;
		}
		}
}

