//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Engine
{
	public class Movement
	{
		private double time;
		private double I; //Moment of Inertia
		private double forwardVelocity;
		private double mass;
		public double FyTotal{ get; set; }
		public double MzTotal{ get; set; }

		public Movement (double FyTotal, double MzTotal, double I, double forwardVelocity, double mass)
		{
			this.forwardVelocity = forwardVelocity;
			this.MzTotal = MzTotal;
			this.FyTotal = FyTotal;
			this.I = I;
			this.mass = mass;
		}
		public double yawVelocity()
		{
			//TO-DO
			double integrated = (MzTotal / I);

			return integrated;
		}
		public double accelerationY()
		{
			//TO CHECK if lateralVelocity is the value here
			double result = (this.FyTotal / mass) - (yawVelocity() * lateralVelocity());
			return result;
		}

		public double lateralVelocity()
		{
			double result = accelerationY() * time;
			return result;
		}




	}
}

