//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Engine
{
	public class Movement
	{
		private double time;
		private double I; //Moment of Inertia
		private double forwardVelocity;

		public double FyTotal{ get; set; }
		public double MzTotal{ get; set; }

		public Movement (double FyTotal, double MzTotal, double I, double forwardVelocity)
		{
			this.forwardVelocity = forwardVelocity;
			this.MzTotal = MzTotal;
			this.FyTotal = FyTotal;
			this.I = I;
		}
		public double yawVelocity()
		{
			double n1 = (MzTotal / I) / time;
			return n1;
		}
		public double accelerationY()
		{
			double result = (FyTotal / mass) - (yawVelocity() * v);
			return result;
		}

		public double lateralVelocity()
		{
			double result = accelerationY * time;
			return result;
		}




	}
}

